package leapgestureanalyzer;

/**
 *
 * @author AndresMauricio
 */
public class Console extends javax.swing.JInternalFrame {

    /**
     * Creates new form HandGestureConsole
     */
    public Console() {
        initComponents();
        mConsoleTextArea.setEditable(false);
        mConsoleTextArea.setText("Output console:");
    }
    
    /**
     * 
     * @param text 
     */
    public void setText(String text) 
    {
        mConsoleTextArea.setText(text);
    }
    
    /**
     * 
     * @param line 
     */
    public void write(String line) 
    {
        mConsoleTextArea.append("\n" + line);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        mConsoleTextArea = new javax.swing.JTextArea();

        setTitle("Output Console");

        mConsoleTextArea.setColumns(20);
        mConsoleTextArea.setRows(5);
        jScrollPane1.setViewportView(mConsoleTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea mConsoleTextArea;
    // End of variables declaration//GEN-END:variables
}
